= Two Types of Company
:page-layout: post
:page-date: 2020-03-07 15:53:00 -0800
:page-tags: [programming, business]

In the years I've spent talking to recruiters and working I've noticed that companies can be separated into two categories.
Yes, it's reductive to categorize every company into two possible groups, but when it comes to compensation I have little sympathy or leeway for corporations.
The two types are very easy to distinguish because the ones you want to avoid identify themselves by using the term "market rate".

== The "Market Rate" Mimics
When a company HR rep. or executive mentions "market rate" what you should hear is "we're going to pay you as little as possible"; "market rate" is little more than honeyed words describing uncoordinated, decentralized, price-fixing of your salary.
These companies are not interested in your experience, improvements you could provide to their long-term business success, your work-life balance, or how your salary stagnates due to inflation.
Their finance department views you and your ilk as an expense to be aggressively minimized because you don't bring in sales; your pay isn't _necessary_ like sales commissions.

You may receive wiggle-room when securing a fraction more vacation time, but the company is vastly ahead when they only need offer minor vacation day increases.
A couple extra vacation days costs the company far less than having to pay for and retain talented programming, quality assurance, and product management staff.
Inevitably this leads to the high turn-over rate we currently see in the industry; 2 years or less at a company then leave for better pay.

== The Talent Retainers
Some companies are _different_ and considered technical staff to be valuable business assets; they see value in employees who know internal systems and can improve long-term business health.
These Talent Retainers do not throw around the term "market rate" because they know it's a negative phrase.
They pay what is reasonable and necessary to keep talent, actively working against brain-drain that plagues other companies.
Their workplace is capable of sustaining higher morale throughout stressful times because employees know they are valued.

There is a stickiness factor to Talent Retainers that leads to incredibly low turn-over rates; talent staying for four or more years is common.
That stickiness shouldn't be surprising since these employees get higher pay, better work-life balance, and have more positive outlooks on their jobs.
All these positives begin with the respect shown to talent in the hiring process and continue through the employment duration.
To me, valuing talent through compensation and treating employees as assets seems to be the obvious way to gain all these workplace benefits, yet my experience thus far is that this is a rarity -- certainly it's not common in my circles.

== Corporate Hoarding
I think there's a simple answer to why Talent Retainers are so rare and "Market Rate" Mimics are populous: executive greed.
Employee salaries are an easily predicted, low jitter, linear, tax deductible expense for corporations.
Any corporation that wants a lower effective tax rate or lower net income to take advantage of government tax credits can simply increase employee salaries; this would also be beneficial to the economy.
Rarely do we see this happen, instead almost with certainty, the executive-level employees receive salary increases to create the deduction the corporation requires -- possibly further increased by dividend pay-outs.

I have a major problem with "Market Rate" Mimics paying out dividend bonuses without providing raises to the talent creating that value.
Any company issuing dividend pay-outs is clearly unconcerned about their operating runway and is generating enough gross income to treat employees better instead of exclusively lining the pockets of the highest paid executives.
Don't work for these companies -- they don't deserve you.

== Take Your Worth
The most important thing you must remember is the company you work for doesn't care about you; co-workers might, your manager might, but not the business.
I've seen plenty of individuals and groups of people terminated solely because the business requires it for one reason or another.
Your experience or loyalty, those statements of "being a family", all of that guarantees you nothing when it comes time to fix operating runway or minimize expenses.

Forget working for those "Market Rate" Mimics because they will pay you as little as possible and treat you as expendable.
Ignore thank-you and gift-based lip-service as acceptable payment for the value you create because only monetary compensation shows a company values you.

Ask for your worth -- it won't ever be handed to you.
