= Missteps Within The Legend of Zelda: Breath of the Wild
:page-layout: post
:page-date: 2020-03-26 22:32:23 -0700
:page-tags: [gaming, legend-of-zelda]

With the second instalment of the series under-way I wanted to take some time to highlight what I consider to be major flaws of the first game.
Lots has been written featuring what people consider to be good aspects of the title, but I don't often find criticism of substance related to issues in the product Nintendo delivered.
Complaints generally circle around mechanics people dislike, but I want to offer constructive criticism and point to solutions that could have made this game far better than what was released.
That's not to say people can't dislike something without providing feedback, however I think this game has received far too much praise while being given a pass on some serious core game-play loop flaws.

== Cooking

If you happen to talk to the right NPC early in the game you find out that cooking is an important mechanic aiding player survival with healing and bonus effects.
An entirely missable introduction to a major open-world mechanic is a design oversight that should not occur in a triple-A title -- player freedom to travel wherever they please is not an excuse to avoid a micro-tutorial for critical components of the game.
Cooking replaces the majority of shop-based item purchases and makes missing this introduction a serious hindrance to experiencing the world.
A short quest to create some kind of soup for a character with a cold could have sufficed as an introduction to the cooking system without creating needless barriers or fetch quests; there's no reason to leave discovery of an important game-play element up to chance.

Cooking problems don't stop at how the designers surface this mechanic because once you begin creating prepared foods and elixirs the terrible interface is constantly present.
To cook anything you must open the inventory screen, have Link hold every recipe ingredient, close the inventory screen, and place the items into the cooking potfootnote:[Don't miss or you get to pick everything up off the ground.].
Enjoy repeating this process ad nauseam until all the foods and elixirs you want have been cooked up because the game offers no solution for quickly creating discovered recipes.
Trial-and-error recipe discovery is reasonable, but skipping recipe book and quick-creation functionality for a mechanic with many ingredient combinations and clunky interface is lazy.

I struggle to understand how Nintendo product management staff considered this to be acceptable -- surely quality assurance would have flagged such an egregious design failure?
A post-mortem on the design failure of the cooking system would be an intriguing read because pointing out these kinds of severe interaction flaws is precisely how quality assurance teams can provide maximum value.

== Combat

Combat game-play has wonderful pacing and momentum with fluidity provided by weapon changes and dynamism through a huge number of possible actions powered by the physics engine.
The designers heavily lean on these positive traits in an attempt to paper over deficiencies in enemy design and variety, but the combat content inevitably becomes stale.
At heart the enemies are simple clones from historically typical Zelda-esque titles featuring richer dungeons with large-scale puzzles and where common enemies are not in the spotlight -- transporting these enemies into an open-world game does not work because they are not designed to be a spotlight element.

Guardians are a spotlight-designed enemy, but were relied upon in great capacity to draw attention away from other enemies which ultimately diminished their effectiveness as a tool to curate the player experience.
In the beginning Guardians are intimidating, high-damage enemies capable of killing the player quickly; they are very threatening, but only because of the player's low health and stamina.
That threat diminishes with increases to player health and stamina, but the psychological intimidation of the Guardian fizzles out rapidly due to encountering them at a high frequency.
Guardians are everywhere you travel and they become just another enemy instead of the formidable machines meant to instil caution and tension.
The Guardian intimidation and threat factors could have been maintained for the entirety of the game had the designers used them sparingly to gently guide players around the open-world.

There was an opportunity to create a more curated experience for players by utilizing the Guardian enemy as a natural wall to impede progression -- one that could have benefited player-driven exploration and writer-driven story.
Guardians could have protected important locations to keep them secure for Ganon and provided an opportunity for enemy scaling by having dynamically generated mechanical forms.
That natural wall to curate a player's open-world experience was never realized, and quite possibly never noticed at all.

== World Design

The world's geography is beautifully laid out with natural feeling topography variations and biome transitions.
The designers even provide a new, well implemented climbing mechanic to traverse the world, but somehow still run into bizarre quality issues.
World biomes come with their own weather probabilities yet many seem heavily weighted toward rain which greatly reduces the usefulness of the climbing mechanic.
Rain is such a problem that many players choose to wait at a fire until the weather has cleared instead of engaging with the game.
Randomized mechanics interfering with player exploration tools created specifically for the game is a huge quality issue.
This seems like it should have been a simple problem to fix -- tweak the weighting of rain for the associated biomes -- but the game shipped anyway.

Exploring the world, and having to find shelter when it rains, wouldn't be so bad if the game content offered things to actually discover.
It has a mostly barren open-world populated by shallow characters which feels like the designers forgot they were making an open-world exploration game.
Open-world titles generally focus on ensuring the player finds something worthwhile when they explore a portion of the map.
Humorous notes and scenes are a well established trope within the Fallout series, but there is no indication of any proactive open-world design in this game.
There are shrines to be found around the world, but aside from the few truly interesting puzzles they are a blur of indistinguishable content; fewer, longer shrines as middle-ground puzzle dungeons would have largely improved the situation.

The shrines are a masterpiece of design work compared to the top-tier laziness that went into approving nine hundred Korok Seeds as open-world content.
A voluminous collectible quest with an intangible reward -- I don't think any reward would justify this level of tedium -- is what players receive instead of a vibrant, populated, interesting world.
Nine hundred Korok Seeds is so absurd that I have to wonder how project management at Nintendo approved the idea.
The beautifully designed landscape falls flat due to these kinds of content decisions and feels as if the designers are saying that the world itself should be enough, that they do not need to provide you with engaging content.

== Open World, Closed Fun

A particular moment during one session while I was exploring has stuck with me and come to define my distaste for how the designers tried, and failed, to forcibly create organic player experiences.
I came across a well-hidden chest, located behind a tree, and to my surprise it contained a magical staff which could throw fireballs.
This was my first encounter with one of the elemental staves and I wanted to see its capabilities, so I began using it in vigour.
I was having tonnes of fun launching fireballs when, rather quickly, it broke, and the fun was over.
Several sessions later the realization occurred to me that the designers didn't prioritize players having fun with weapons because they had to solve the larger problem of forcing interaction with bland enemies.
Weapon durability leading to permanent loss is simply the means chosen to reach their goal: having the player engage enemies that, in general, aren't worth the time.

I wonder if anybody reflected on the design choices on display here because they clearly are interrelated with one bad decision leading to another.
Did anyone stop and ask how the game is made better by controlling the duration of fun a player experiences with a weapon?
Weapons a player finds fun will degrade quickly from use, so the game design indicates that the player should have minimal fun with weapons they enjoy.
Degradation and mid-battle weapon breaking certainly create additional dynamism in combat, but I don't think there's a single argument that can be made for permanent weapon destruction being better.

A weapon repair or upgrade system mirroring armour upgrades could easily have provided the same dynamic combat without time boxing player fun.
The weapon and armour systems could have relied on the same resources to create contention -- similar to stamina and health -- which would have provided additional pressure to engage with enemies.
Weapon diversity could have been increased and upgrades or new weapons could have been milestones to work toward, all of which provide more pressure to engage with the world.
Instead the game is populated by mostly identical weapons that differ in look and damage numbers and offer no pressure to interact with the world.

== Player Unfocused

I want to be clear that I think the engineering team for The Legend of Zelda: Breath of the Wild did an amazing job creating the world itself, and I do not want to diminish their accomplishment.
Being able to travel anywhere on the map without loading screens or latency, the smooth weather transitions, and draw distances showing off gorgeous vistas are great feats of engineering.
It's the mediocre game design I dislike and I believe it's only the Zelda brand and the game engine preventing the title from being considered an abject failure.

I'm not sure if the quality assurance team was ignored or absent, but it's clear that the design team needed help recognizing flaws.
I hope Nintendo is embarrassed by these mistakes because the company that scraps a Metroid title for not being fun enough shouldn't also be releasing an open-world game with the majority of content being nine hundred Korok Seeds.
Unfortunately Nintendo has no reason to consider changing anything since the game sold so many copies.
As a corporation, they learnt a low effort, mediocre open-world title makes them tonnes of money as long as they slap the Zelda brand onto it.
Mediocrity isn't where I want to see the franchise end up, but with glowing reviews, a rabid fan-base, and massive profits, it's difficult to see anything changing.
