= A Decade After Alan Wake
:page-date: 2020-01-30 17:18:15 -0800
:page-layout: post
:page-tags: [gaming, alan-wake]
:page-spoiler: This article contains details about the plot, game mechanics, +
    and atmosphere of Alan Wake which will spoil most of the game if you +
    intend to play it.


Ten years since Alan Wake originally released on consoles and I still think it's
Remedy Entertainment's best game, and one of the most ambitious games ever made.
There's little doubt in my mind: it will continue to be one of the best games
I've played for decades to come. This is a game that has been subconsciously
gnawing at me since I played it; the blend of intricate plot, novel tweaks to
game mechanics, and the oppressive atmosphere deliver a superb experience. If
you haven't played it, I suggest you do so immediately, because skipping Alan
Wake is a massive disservice to yourself.


== Have You Got a Light?

Almost everything you do within Alan Wake relates to using light to vanquish the
darkness consuming people and objects of the world. Defeating the Dark Presence
isn't accomplished by just shooting enemies while running around sets: you need
to burn away the protective dark barrier around the Taken and possessed objects
before they can be defeated. This change is what really sets Alan Wake apart from
almost every other action-adventure game; all enemies remain a threat while
protected by the Dark Presence.

More novelty is found in the weapon choices used in the game; things normally
ignored by the majority of shooters become very important. Non-deadly weapons,
like flash-bang grenades, flares, and flare guns are the bread-and-butter of
every playthrough, and give players the ability create strategies around space
management. Using light is further worked into exploration by discovering directions
to resource caches in phosphorescent paint.

This kind of radical shift in available weaponry is still a fresh experience
today; the shooters produced by the triple-A industry are continuing to be
incredibly uniform in style and content.


== Dark Lustre

The atmosphere around Bright Falls consistently delivers for the entire game, and
the transitions from idyllic small town during day-time into a malicious night-time
horror play on the fear of the dark everyone experiences as a child. The exploration
segments are visually and mentally engaging as you journey through the darkness
and fog while keeping an eye out for lurking enemies.

The enemies and set pieces have enough variety and combinations that they're never
boring; all the enemies, being workers of the surrounding areas, are connected to
the locations you visit. Each location is connected to others quite seamlessly:
you must find ways to avoid obstacles, take trails around large ravines to arrive
at destinations beyond, and as always in Alan Wake, move away from the darkness
toward the light.

The beautiful coincidence of the visual design choice made within Alan Wake,
darkness and fog being the main driver of action-oriented segments, is it has aged
gracefully. It still looks good playing it today on a 4K monitor, however, the
cut-scene videos are showing a bit of age, as the up-scaling causes artefacts. It's
not something that is terribly jarring, and the musical score immediately makes
up for it.

Remedy Entertainment hired a real band, Poets of the Fall, to write the music for
the in-world band Old Gods of Asgard. Old Gods of Asgard create songs with lyrics
that tie directly into the plot of the game. The music both as background to the
experience and part of the narrative is something I have yet to experience in any
other title.


== Malleable Reality

The best part of Alan Wake for me is the intricate story, unfolding in small,
reality-bending chunks. Very few games attempt such an ambitious story, and fewer
still managed to create something cohesive out of them. Alan Wake's story doesn't
attempt to answer every question that arises from the events of the game, but those
loose ends are precisely what gives the story longevity.

The story unfolds around a magical lake where writers can turn their creations into
reality, but there is a malevolent entity present around the lake as well. This
entity wants to be free of its prison and attempts to use several people to write
its freedom; two of which are Thomas Zane and Alan Wake.

The story itself has multiple protagonists, but focuses on the immediate experiences
of only Alan Wake. The events of the story are set up by several individuals: Thomas
Zane, Cynthia Weaver, the Anderson brothers, and Alan Wake himself. Each person
plays a crucial role in the events leading up to obtaining a broken light-switch
from Alan's childhood called the Clicker. Zane creates the Clicker, Cynthia guards
it, Alan must acquire it, and the Anderson brothers guide Alan to it.

The moment Alan retrieves the Clicker is pivotal to the story because it temporally
links Zane to Alan. Inside the shoebox, Zane has placed a page of writing, brought
into reality by the magic of the lake, which creates the Clicker as part of Alan's
childhood -- prior to this, Zane had written himself and the entity out of reality;
only Zane's possessions which were already stored within a shoebox would remain.
With this action Zane demonstrates that the power of the lake is capable of altering
past and future realities: he removes himself and all his work from the world and
modifies a reality that has not come to pass. Zane takes things a step further
by placing the Clicker both in a shoebox for Cynthia to guard and into Alan's life,
potentially creating an object capable of bi-location.

Yet all of what we experience within the game is Alan's writing: every battle,
roadblock, and set-back the Dark Presence creates is part of the story Alan writes
to escape. The journey itself is of Alan's design, but the destinations have been
laid out in advance by Zane. Not to be outdone, Alan creates an intriguing ending
to his own personal horror story: his escape and harrowing adventure all must lead
him back to the cabin to complete the final page. Finishing his story can only be
undertaken by making the story reality and experiencing it until its penultimate
scene. Alan's story blends reality and story together until they are indistinguishable;
he creates a mobius strip of seamlessly blended reality and fiction.

There are two pages I think tie directly into the mobius-strip-story idea; one
is only found in Nightmare Mode, which reads as follows:

[quote, Wake Reads a Page]
____
I lifted the page in front of my eyes and read it. In it, I lifted the page in
front of my eyes and read it. In it, I lifted the page in front of my eyes and
read it. In it, I lifted the page in front of my eyes and read it. In it, I
lifted the page in front of my eyes and read it. In it, I lifted the page in
front of my eyes and read it.
____

The other is available as part of the story itself:

[quote, Nightingale Reads the Manuscript]
____
Nightingale tried to make sense of the manuscript. It was disjointed and strange.
He didn't understand half of it, but it all rang true, impossibly true.

He took out his hip flask when he reached the page that described how he reached
the page that made him take out his hip flask.

It wasn't the booze that made his mind reel.
____

Both of these pages imply that the power of the lake is also capable of causing
people to take specific actions; actions which Wake has already written and are
coming to pass, as the script is played out. Nearly all of Alan's story revolves
around actions he takes, and he is essentially guiding himself to finish the story
within the story, but to guide himself to that realized ending necessitates an
already completed story. The Writing-Alan must have written the ending for
Acting-Alan to undertake, but Acting-Alan eventually finishes the story to become
Writing-Alan. If the story can only be finished within itself, Writing-Alan must
have previously have been Acting-Alan. The game's story seems to take place within
a recursive framework of actions relying on previous Writer-Alans which rely on
previous Actor-Alans which rely on previous Writer-Alans.

This seems to be the best way to defeat the Dark Presence, as it is capable of
eventually returning from the Dark Place. Instead of attempting, like Zane or the
Anderson brothers, to put it back to sleep, Alan traps it in a time-loop of events
it is required to play out while freeing Alice at the moment the time-loop begins.
Is there any actual proof of that? None at all, but that kind of speculation is
what keeps this story so interesting to me.

Many more things occur within the story, but these highlight what I think is best
about it: there is subtlety and depth to the plot of Alan Wake that remains unmatched
by the majority of games ever created. Alan Wake shows some of the heights that
video games are capable of when used as a medium for interactive story-telling.


== Reach the Lighthouse

There won't ever be enough time to explore every game, but I think that Alan Wake
is one that deserves attention -- especially if you enjoy horror-thriller. If the
novel weaponry in the game isn't enough to intrigue you, the full story definitely
should keep your interest. Reach the lighthouse, finish the game, and decide for
yourself https://www.youtube.com/watch?v=GLxb7m0j5Jg[if it's real or just a dream].

