#!/bin/sh
set -o pipefail

trap "rm tmp/purge_urls_*" EXIT

urls_to_purge | split -l 30 - 'tmp/purge_urls_'

for f in $(find tmp -name 'purge_urls_*'); do
  curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
    -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
    -H "Content-Type: application/json" \
    --data "$(cat "$f" | urls_as_json)"
done
