#!/bin/bash
set -e

post_file="$(select_draft_post)"
if [[ -z "$post_file" ]]; then
	echo "No draft posts."
	exit 0
fi

echo "Publishing \"$(extract_post_title "$post_file")\""
now="$(date -uIseconds | sed 's/[+-]00:00/Z/')"
sed -i -e '/^draft: true$/d' -e 's/^date: ".\+"$/date: "'$now'"/' "$post_file"
